### ISSUE TITLE
JSONException

### ISSUE THREAD

**Issue by solokingjec** [Ritaja/java-exchange-rates#4]
Hello. 
Am getting this error when calling method..
BigDecimal amount = converter.convertCurrency(new BigDecimal("1"), "USD", "KES");

Severe:   org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at com.ritaja.xchangerate.service.HttpserviceImpl.getResponse(HttpserviceImpl.java:45)
	at com.ritaja.xchangerate.endpoint.EndpointFactory.sendLiveRequest(EndpointFactory.java:42)
	at com.ritaja.xchangerate.api.CurrencyConverter.updateResource(CurrencyConverter.java:85)
	at com.ritaja.xchangerate.api.CurrencyConverter.convertCurrency(CurrencyConverter.java:56)
	at service.MeridesWeb.checkRates(MeridesWeb.java:413)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by vetal232** [comment]
Yahoo Finance API Service is down and closed. So, this error you got due to unavailable to download JSON with currency data from yahoo.
